---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dokuwiki-placement
  labels:
    app: dokuwiki-sample
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterReplicas: 1
  schedulerName: "ramen"
