apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki
  namespace: dokuwiki
  labels:
    appname: dokuwiki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 1Gi
