---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  namespace: busybox-sample
  labels:
    app: busybox-sample
spec:
  preferredCluster: "tflow-rmn-aws-cluster5"
  action: "Failover"
  failoverCluster: "tflow-rmn-aws-cluster5"
  drPolicyRef:
    name: dr-policy
    namespace: ramen-samples
  placementRef:
    kind: PlacementRule
    name: busybox-placement
  pvcSelector:
    matchLabels:
      appname: busybox
