---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-drpc
  labels:
    app: busybox-sample
spec:
  preferredCluster: "mgd1"
  failoverCluster: "local-cluster"
  drPolicyRef:
    name: drpolicy-sample
    namespace: ramen-samples
  placementRef:
    kind: PlacementRule
    name: busybox-placement
  pvcSelector:
    matchLabels:
      appname: busybox
