---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc1-cephfs
  labels:
    appname: busybox
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "ocs-storagecluster-cephfs"
  resources:
    requests:
      storage: 1Gi
